spring.application.name=shipmenttracker
# Set root logging level to WARN (shows only WARN, ERROR, FATAL)
logging.level.root=WARN
# Optionally silence specific packages (e.g., Hibernate, Tomcat)
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
spring.main.banner-mode=off

# If using WebSocket, reduce noise from that too
logging.level.org.springframework.web=WARN

spring.datasource.url=jdbc:h2:mem:shipmentdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080

logging.level.com.example.shipmenttracker=DEBUG
logging.level.org.springframework.messaging=DEBUG